/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolVerifyRouteImport } from './routes/school-verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MonthRouteImport } from './routes/month'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSyllabusRouteImport } from './routes/admin.syllabus'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolVerifyRoute = SchoolVerifyRouteImport.update({
  id: '/school-verify',
  path: '/school-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthRoute = MonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyllabusRoute = AdminSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/month': typeof MonthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/school-verify': typeof SchoolVerifyRoute
  '/schools': typeof SchoolsRoute
  '/sections': typeof SectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/syllabus': typeof AdminSyllabusRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/month': typeof MonthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/school-verify': typeof SchoolVerifyRoute
  '/schools': typeof SchoolsRoute
  '/sections': typeof SectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/syllabus': typeof AdminSyllabusRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/month': typeof MonthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/school-verify': typeof SchoolVerifyRoute
  '/schools': typeof SchoolsRoute
  '/sections': typeof SectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/syllabus': typeof AdminSyllabusRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/month'
    | '/profile'
    | '/register'
    | '/school-verify'
    | '/schools'
    | '/sections'
    | '/sitemap.xml'
    | '/admin/instructors'
    | '/admin/profile'
    | '/admin/schools'
    | '/admin/syllabus'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/month'
    | '/profile'
    | '/register'
    | '/school-verify'
    | '/schools'
    | '/sections'
    | '/sitemap.xml'
    | '/admin/instructors'
    | '/admin/profile'
    | '/admin/schools'
    | '/admin/syllabus'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/month'
    | '/profile'
    | '/register'
    | '/school-verify'
    | '/schools'
    | '/sections'
    | '/sitemap.xml'
    | '/admin/instructors'
    | '/admin/profile'
    | '/admin/schools'
    | '/admin/syllabus'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  MonthRoute: typeof MonthRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SchoolVerifyRoute: typeof SchoolVerifyRoute
  SchoolsRoute: typeof SchoolsRoute
  SectionsRoute: typeof SectionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-verify': {
      id: '/school-verify'
      path: '/school-verify'
      fullPath: '/school-verify'
      preLoaderRoute: typeof SchoolVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/syllabus': {
      id: '/admin/syllabus'
      path: '/syllabus'
      fullPath: '/admin/syllabus'
      preLoaderRoute: typeof AdminSyllabusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminSyllabusRoute: typeof AdminSyllabusRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminSyllabusRoute: AdminSyllabusRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  MonthRoute: MonthRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SchoolVerifyRoute: SchoolVerifyRoute,
  SchoolsRoute: SchoolsRoute,
  SectionsRoute: SectionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
